# Generated by Django 6.0.6 on 2026-06-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
