# Generated by Django 6.0.6 on 2026-06-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_App', '0002_rename_update_at_appointment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
    ]
