# Generated by Django 6.0.6 on 2026-06-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_App', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
