# Generated by Django 6.0.7 on 2026-07-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0002_remove_donor_created_at_remove_donor_updated_at'),
        ('hospitals', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Cornea', 'Cornea'), ('Bone Marrow', 'Bone Marrow')], max_length=50)),
                ('donation_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_donations', to='donors.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_donations', to='hospitals.hospital')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_organs', to='recipients.recipient')),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
